-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvbpbWZwo2GxfDXpu
wJj8MCFdaIHEB4qkgwAfjHl/pS+gCgYIKoZIzj0DAQehRANCAATDWHeGbBurN12X
x3G4zklHWetygsb1SxpGdxoVhLhR2RLfpZ+umvNS7REbXhWmgt/VmEqf+1GeiXT8
WsMyxKzh
-----END PRIVATE KEY-----