-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcfndUpJNQSg5nl4J
55VbkjrNt/xgQwYKqyJzzq5FVkygCgYIKoZIzj0DAQehRANCAASy1kPCLZ5RI62n
wlXcHw3UJGGlJ/grAcfzaOEAuNsZsstAQ/siUq1FCJls7bPTH7QlMv4OMDZzDY2y
5k1YGh6X
-----END PRIVATE KEY-----