workflows:
  ios-release:
    name: Build iOS release
    environment:
      vars:
        FLUTTER_BUILD_MODE: release
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
      flutter: stable
      xcode: 16.2
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - .dart_tool
    scripts:
      - name: Instalar dependencias Flutter
        script: flutter pub get

      - name: Instalar dependencias iOS (Pods)
        script: |
          cd ios
          pod install

      - name: Compilar Flutter para iOS
        script: flutter build ios --release --no-codesign

      - name: Compilar y exportar IPA para App Store
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/ios/archive/Runner.xcarchive \
            -configuration Release \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=Y82Q48DSZ2 \
            COMPILER_INDEX_STORE_ENABLE=NO archive

          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
          private_key: $APP_STORE_PRIVATE_KEY



