workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: release
        APPLE_CERTIFICATE_PASSWORD: $APPLE_CERTIFICATE_PASSWORD
        IOS_DISTRIBUTION_P12: $IOS_DISTRIBUTION_P12
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Decode and prepare .p12 file
        script: |
          echo $IOS_DISTRIBUTION_P12 | base64 --decode > ios_distribution.p12
      - name: Build iOS app
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
          private_key: $APP_STORE_PRIVATE_KEY
        submit_to_app_store: true
