workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.manuelnavarro.assistifyapp

    integrations:
      app_store_connect: assistifyaibo

    scripts:
      - name: Instalar dependencias
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install --verbose
          cd ..

      - name: Verificar perfiles instalados
        script: |
          echo "🔐 Perfiles disponibles:"
          security find-identity -v
          profiles list

      - name: Importar certificado
        script: |
          keychain add-certificates

      - name: Inicializar llavero y configurar perfil
        script: |
          keychain initialize
          xcode-project use-profiles

      - name: Verificar esquemas disponibles
        script: |
          xcodebuild -list -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE"

      - name: Verificar configuración del esquema
        script: |
          xcodebuild -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$XCODE_CONFIGURATION" \
            -showBuildSettings | grep -i configuration

      - name: Mostrar configuración de Xcode
        script: |
          xcodebuild -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" -showBuildSettings

      - name: Compilar Flutter para iOS
        script: |
          flutter build ios --release --build-name=2.0.14 --build-number=82

      - name: Compilar IPA manualmente (debug detallado)
        script: |
          xcodebuild -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=Y82Q48DSZ2 \
            COMPILER_INDEX_STORE_ENABLE=NO | tee build.log | xcpretty || { cat build.log; exit 1; }


    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.ipa
      - build/ios/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
