workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify
      flutter: stable

    integrations:
      app_store_connect: assistifyfinal

    signing:
      certificates:
        - path: Certificates/ios_distribution.p12
          password: $P12_CERTIFICATE_PASSWORD
      provisioning_profiles:
        - Certificates/Assistify_Prod_Profile.mobileprovision

    scripts:
      - name: Verificar contenido del provisioning profile
        script: |
          echo "📄 Contenido del provisioning:"
          security cms -D -i Certificates/Assistify_Prod_Profile.mobileprovision || echo "⚠️ No se pudo leer el profile"

      - name: Instalar dependencias
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Compilar IPA para producción
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
