workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2  # Definimos el tipo de instancia para la build
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - app_store_credentials  # Asegurar que las variables de entorno sean accesibles

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: "5X2C57X263"
          issuer_id: "a42f6d03-89a5-4f05-a1e9-449150a57f9b"
          private_key: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgO2RVVeZ0Ev7H69sK
            ZOENMu0K+j3djDGk2uGmePZdF8ugCgYIKoZIzj0DAQehRANCAATChMt4cc3ogrv3
            Xd/tQdPGD5fq+age1aRgkR8LVHZeZShv4X9tOMBFk+k7BnB1FLXzZYWh5bHMncI0
            phOlex2p
            -----END PRIVATE KEY-----
        submit_to_app_store: true
