workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.manuelnavarro.assistifyapp

    integrations:
      app_store_connect: assistifyaibo

    scripts:
      - name: Instalar dependencias
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Importar certificado
        script: |
          keychain add-certificates

      - name: Configurar firma automática
        script: |
          keychain initialize
          xcode-project use-profiles

      - name: Compilar IPA para producción
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Mostrar contenido de build/ios
        script: |
          echo "Contenido de build/ios:"
          ls -l build/ios

      - name: Verificar si se generó el .ipa
        script: |
          echo "Buscando IPA en build/ios..."
          find build/ios -name "*.ipa"

    artifacts:
      - build/ios/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
