workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
 
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: "5X2C57X263"
          issuer_id: "a42f6d03-89a5-4f05-a1e9-449150a57f9b"
          private_key: |
            -----BEGIN PRIVATE KEY-----
            TU_CLAVE_PRIVADA_AQUI
            -----END PRIVATE KEY-----
        submit_to_app_store: true
