workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_MODE: release
        APPLE_CERTIFICATE_PASSWORD: $APPLE_CERTIFICATE_PASSWORD
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: 
          key_id: VMPYZM4P66 # Reemplaza con tu nuevo Key ID
          issuer_id: a42f6d03-89a5-4f05-a1e9-449150a57f9b # Tu Issuer ID
          private_key: $APP_STORE_PRIVATE_KEY # Variable de entorno para la clave privada
        submit_to_app_store: true
