workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2

    auto_code_signing:
      signing_certificate: "Apple Distribution"
      team_id: Y82Q48DSZ2
      app_identifier: com.manuelnavarro.assistifyapp


    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify

    integrations:
      app_store_connect: assistifyfinal

    scripts:
      - name: Instalar dependencias
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Compilar IPA para producción
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
