workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2  
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify  # Asegúrate de que este grupo tenga las credenciales correctas

    integrations:
      app_store_connect: assistifyfinal  # Vincula Codemagic con App Store Connect

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration  # Usa la integración configurada
        submit_to_app_store: true  # Enviar a App Store Connect automáticamente
        submit_to_testflight: true    # Enviar a App Store Connect automáticyamente
