workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.manuelnavarro.assistifyapp

    integrations:
      app_store_connect: assistifyaibo

    scripts:
      - name: Instalar dependencias
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Importar certificado
        script: |
          keychain add-certificates

      - name: Inicializar llavero y configurar perfil
        script: |
          keychain initialize
          xcode-project use-profiles

      # 🔍 Paso 4: Mostrar esquemas disponibles en el workspace
      - name: Verificar esquemas disponibles
        script: |
          xcodebuild -list -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE"

      # 🔍 Paso 5: Mostrar configuración de Xcode
      - name: Mostrar configuración de Xcode
        script: |
          xcodebuild -workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" -showBuildSettings

      - name: Compilar y exportar IPA para App Store
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: Mostrar contenido de build/ios
        script: |
          echo "Contenido de build/ios:"
          ls -l build/ios

      - name: Mostrar contenido de build/ios/ipa
        script: |
          echo "Contenido de build/ios/ipa:"
          ls -l build/ios/ipa || echo "No existe la carpeta ipa"

      - name: Verificar si se generó el .ipa
        script: |
          echo "Buscando IPA en build/ios..."
          find build/ios -name "*.ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.ipa
      - build/ios/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
