workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2  # Definimos el tipo de instancia para la build
    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
          private_key: $APP_STORE_PRIVATE_KEY
        submit_to_app_store: true
