workflows:
  ios-workflow:
    name: "iOS Build"
    max_build_duration: 60
    instance_type: mac_mini_m2  

    environment:
      vars:
        FLUTTER_BUILD_MODE: "release"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - Assistify  # Asegurate de que este grupo tenga las credenciales correctas
      flutter: stable

    integrations:
      app_store_connect: assistifyfinal  # Ya tenés esta integración activa



    scripts:
      - name: Verificar contenido del .mobileprovision
        script: |
          echo "📄 Imprimiendo contenido del provisioning profile..."
          security cms -D -i Certificates/assistifyaibo.mobileprovision || echo "❌ No se pudo leer el provisioning profile"

      - name: Instalar dependencias
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Compilar IPA para producción
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist


    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        submit_to_testflight: true
