name: taller_ceramica
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.16+84

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  chewie: ^1.8.5
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.8.0
  go_router: ^14.6.1
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  in_app_purchase: ^3.0.0
  intl: ^0.19.0
  ntp: ^2.0.0
  path: ^1.9.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.1
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false # En Windows, esto debe estar en false
  remove_alpha_ios: true
  image_path: "assets/icon/aicon.png"
  adaptive_icon_foreground: "assets/icon/aicon.png"
  adaptive_icon_background: "assets/icon/background.png"
  web:
    generate: true
    image_path: "assets/icon/aicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icon/
    - .env

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
