require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

platform :ios, '12.0'

use_frameworks! :linkage => :static
install! 'cocoapods', :disable_input_output_paths => true
inhibit_all_warnings!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(__FILE__)

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end
end
