require_relative '../Flutter/flutter_export_environment'
load File.join(__dir__, 'Flutter', 'Generated.xcconfig')

platform :ios, '12.0'

use_frameworks! :linkage => :static
install! 'cocoapods', :disable_input_output_paths => true
inhibit_all_warnings!

target 'Runner' do
    install_all_flutter_pods(File.dirname(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end
end
